server.port=15900
server.servlet.context-path=/

# 禁用 Eureka
eureka.client.register-with-eureka=false
eureka.client.fetchRegistry=false

# 使用远程 MongoDB
spring.data.mongodb.uri=mongodb://172.28.0.81:27017/engine-scm?connectTimeoutMS=30000&socketTimeoutMS=30000

# 禁用配置中心
spring.config.import=

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Swagger
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true

# Actuator
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/
management.endpoint.health.show-details=always
management.security.enabled=false