
server.port=15900
server.servlet.context-path=/

#info
info.app.name=engine-scm
info.app.description=引擎配置管理
info.app.version=1.0.x
info.app.spring-boot-version=2.7.18

#actuator
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/
management.endpoint.health.show-details=always
management.info.git.mode=full
management.security.enabled=false

eureka.instance.prefer-ip-address=true
eureka.instance.metadata-map.configPath=${server.servlet.context-path}
eureka.instance.metadata-map.version=1.0.x
eureka.instance.metadata-map.name=引擎配置管理
eureka.instance.status-page-url-path=${server.servlet.context-path}/info
eureka.instance.health-check-url-path=${server.servlet.context-path}/health
eureka.instance.home-page-url=${server.servlet.context-path}

spring.data.mongodb.uri=mongodb://172.28.0.81:27017/engine-scm?connectTimeoutMS=30000;socketTimeoutMS=30000

spring:
thymeleaf:
cache: false
prefix: classpath:/templates/
suffix: .html

spring.config.import= optional:configserver:
#eureka.client.serviceUrl.defaultZone=http://xxx/eureka
eureka.client.register-with-eureka=false
eureka.client.fetchRegistry=false

springdoc:
api-docs:
enabled: true
path: /v3/api-docs

swagger-ui.path=/swagger-ui.html
swagger-ui.path.operationsSorter=method
swagger-ui.path.tagsSorter=alpha
swagger-ui.path.display-request-duration=true
